name: my_gallery_task
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-42.2.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  flutter_staggered_animations: ^1.1.1
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  http: ^1.1.0
  shared_preferences: ^2.2.1
  cached_network_image: ^3.3.0
  fluttertoast: ^8.2.2
  carousel_slider: ^4.2.1
  connectivity_plus: ^5.0.1
  injectable: ^2.1.0 # Version 2
  json_annotation: ^4.7.0
  # add get_it
  get_it: ^7.6.7
  flutter_image_slideshow: ^0.1.6
  readmore: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  build_runner: ^2.3.3
  injectable_generator: ^2.1.3 # Version 2
  json_serializable: ^6.5.4
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/


  fonts:
    - family: MyCustomFont
      fonts:
        - asset: assets/fonts/segoe.ttf
          weight: 500
        - asset: assets/fonts/segoe_bold.ttf
          weight: 700
